# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "makey105"
product_name = "makey105"
vendor_id = 0xFEED
product_id = 0x6060
manufacturer = "mark1028"
chip = "nrf52840"
usb_enable = true

[matrix]
# Input and output pins are mandatory
input_pins = ["P0_10", "P1_06", "P1_04", "P1_02", "P0_30", "P1_11"]
output_pins = ["P0_17", "P0_20", "P0_22", "P1_00", "P0_12", "P1_09", "P0_08", "P0_05", "P0_06", "P0_26", "P0_31", "P0_29", "P0_15", "P0_02", "P1_13", "P0_28", "P0_03", "P1_10", "P0_09"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 6
cols = 19
layers = 4
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7) (0,8) (0,9) (0,10) (0,11) (0,12) (0,13) (0,14) (0,15) (0,16) (0,17) (0,18)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7) (1,8) (1,9) (1,10) (1,11) (1,12)        (1,14) (1,15) (1,16) (1,17) (1,18)
(2,0)       (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (2,8) (2,9) (2,10) (2,11) (2,12) (2,13) (2,14) (2,15) (2,16) (2,17)  
(3,0)       (3,2) (3,3) (3,4) (3,5) (3,6) (3,7) (3,8) (3,9) (3,10) (3,11) (3,12)        (3,14) (3,15) (3,16) (3,17) (3,18)
(4,0)       (4,2) (4,3) (4,4) (4,5) (4,6) (4,7) (4,8) (4,9) (4,10) (4,11)        (4,13) (4,14) (4,15) (4,16) (4,17)  
(5,0) (5,1) (5,2) (5,3) (5,4) (5,5) (5,6) (5,7) (5,8) (5,9) (5,10) (5,11)        (5,13) (5,14) (5,15) (5,16) (5,17) (5,18)
"""

# layer 0 :
[[layer]]
name = "default_layer" #optional name for the layer
keys = """
Escape   F1   F2   F3  F4   F5  F6  F7  F8  F9    F10  F11       F12         PrintScreen  Delete    Home    End     PageUp     PageDown        
Grave    Kc1  Kc2  Kc3 Kc4  Kc5 Kc6 Kc7 Kc8 Kc9   Kc0  Minus     Equal       No           Backspace NumLock KpSlash KpAsterisk KpMinus
Tab      No   Q    W   E    R   T   Y   U   I     O    P         LeftBracket RightBracket Backslash Kp7     Kp8     Kp9        No
CapsLock No   A    S   D    F   G   H   J   K     L    Semicolon Quote       No           Enter     Kp4     Kp5     Kp6        KpPlus
LShift   No   Z    X   C    V   B   N   M   Comma Dot  Slash     No          RShift       Up        Kp1     Kp2     Kp3        No
LCtrl    LGui LAlt A  Space B   C   D   E   RAlt  RGui RCtrl     No          Left         Down      Right   Kp0     KpDot      Enter
"""

# layer 1 :
[[layer]]
name = "Photoshop_layer" #optional name for the layer
keys = """
Escape   F1    F2    F3    F4    F5    F6    F7  F8  F9    F10  F11       F12         PrintScreen  Delete    Home    End     PageUp     PageDown        
Grave    User0 User1 User2 User3 User4 User5 Kc7 Kc8 Kc9   Kc0  Minus     Equal       No           Backspace NumLock KpSlash KpAsterisk KpMinus
Tab      No    Q     W     E     R     T     Y   U   I     O    P         LeftBracket RightBracket Backslash Kp7     Kp8     Kp9        No
CapsLock No    A     S     D     F     G     H   J   K     L    Semicolon Quote       No           Enter     Kp4     Kp5     Kp6        KpPlus
LShift   No    Z     X     C     V     B     N   M   Comma Dot  Slash     No          RShift       Up        Kp1     Kp2     Kp3        No
LCtrl    LGui  LAlt  A     Space B     C     D   E   RAlt  RGui RCtrl     No          Left         Down      Right   Kp0     KpDot      Enter
"""

# layer 2 :
[[layer]]
name = "eda_layer" #optional name for the layer
keys = """
Escape   F1   F2   F3  F4   F5  F6  F7  F8  F9    F10  F11       F12         PrintScreen  Delete    Home    End     PageUp     PageDown        
Grave    Kc1  Kc2  Kc3 Kc4  Kc5 Kc6 Kc7 Kc8 Kc9   Kc0  Minus     Equal       No           Backspace NumLock KpSlash KpAsterisk KpMinus
Tab      No   Q    W   E    R   T   Y   U   I     O    P         LeftBracket RightBracket Backslash Kp7     Kp8     Kp9        No
CapsLock No   A    S   D    F   G   H   J   K     L    Semicolon Quote       No           Enter     Kp4     Kp5     Kp6        KpPlus
LShift   No   Z    X   C    V   B   N   M   Comma Dot  Slash     No          RShift       Up        Kp1     Kp2     Kp3        No
LCtrl    LGui LAlt A  Space B   C   D   E   RAlt  RGui RCtrl     No          Left         Down      Right   Kp0     KpDot      Enter
"""

# layer 3 :
[[layer]]
name = "davinci_layer" #optional name for the layer
keys = """
Escape   F1   F2   F3  F4   F5  F6  F7  F8  F9    F10  F11       F12         PrintScreen  Delete    Home    End     PageUp     PageDown        
Grave    Kc1  Kc2  Kc3 Kc4  Kc5 Kc6 Kc7 Kc8 Kc9   Kc0  Minus     Equal       No           Backspace NumLock KpSlash KpAsterisk KpMinus
Tab      No   Q    W   E    R   T   Y   U   I     O    P         LeftBracket RightBracket Backslash Kp7     Kp8     Kp9        No
CapsLock No   A    S   D    F   G   H   J   K     L    Semicolon Quote       No           Enter     Kp4     Kp5     Kp6        KpPlus
LShift   No   Z    X   C    V   B   N   M   Comma Dot  Slash     No          RShift       Up        Kp1     Kp2     Kp3        No
LCtrl    LGui LAlt A  Space B   C   D   E   RAlt  RGui RCtrl     No          Left         Down      Right   Kp0     KpDot      Enter
"""

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
capslock.pin = "P0_24"
capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
numslock.pin = "P0_13"
numslock.low_active = true

[ble]
enabled = true
battery_adc_pin = "P0_04"
# charge_state.pin = "P0_07"
# charge_state.low_active = true
# charge_led.pin = "P0_08"
# charge_led.low_active = false
adc_divider_measured = 2000
adc_divider_total = 2820


[storage]
# Storage feature is enabled by default
# enabled = false

# Whether to use the MCU's internal pull-up resistor, default to false 是否使用MCU的内部上拉电阻，默认为false
#internal_pullup = true  # 使用mcu内部上拉电阻
#low_active = true

[rmk]
# The number of available BLE profiles 配对蓝牙设备的数量
ble_profiles_num = 6
